'use strict';var l,aa=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},ca=ba(this),da=function(a,b){if(b)a:{var c=ca;a=a.split(".");
for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&aa(c,a,{configurable:!0,writable:!0,value:b})}},m=function(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})};da("globalThis",function(a){return a||ca});
da("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&c.push([d,b[d]]);return c}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var n=this||self,ea=function(a){var b=typeof a;b=b!="object"?b:a?Array.isArray(a)?"array":b:"null";return b=="array"||b=="object"&&typeof a.length=="number"},p=function(a){var b=typeof a;return b=="object"&&a!=null||b=="function"},fa=function(a,b,c){return a.call.apply(a.bind,arguments)},ha=function(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,
e)}}return function(){return a.apply(b,arguments)}},q=function(a,b,c){q=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?fa:ha;return q.apply(null,arguments)},r=function(a,b){function c(){}c.prototype=b.prototype;a.Ja=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ha=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}};var t="getAccounts hello getLogBuffer recordLog getQuirks updateQuirks uiEvent proxyUIEvent getProxyConfig".split(" ");var oa=function(a){switch(a){case ia.name:return ia;case ja.name:return ja;case ka.name:return ka;case la.name:return la;case ma.name:return ma;default:let b=na.get(a);b||(b=new u(a),na.set(a,b));return b}},u=class{constructor(a){this.name=a}toString(){return this.name}},na=new Map,ia=new u("async"),ja=new u("generic"),ka=new u("runtime"),la=new u("system"),ma=new u("crypto"),pa=class extends Error{constructor(a,b,c){super(c);this.code=a;this.category=b;Object.setPrototypeOf(this,new.target.prototype)}toString(){return`${this.category}:${this.code} (${this.message||
"Undefined error."})`}};var qa=class{constructor(){let a=void 0,b=void 0;this.promise=new Promise((c,d)=>{a=c;b=d});this.resolve=a;this.reject=b}},ra=class extends pa{constructor(a,b="One or more errors occurred."){super(1,ia,b);this.errors=a;Object.setPrototypeOf(this,new.target.prototype)}flatten(){const a=[],b=[this.errors.slice(0)];for(;b.length!==0;){const c=b[0];for(;c.length!==0;){const d=c.shift();if(d instanceof ra){b.unshift(d.errors.slice(0));break}else a.push(d)}b[0]===c&&b.shift()}return new ra(a,this.message)}};var sa=class{constructor(){this.A=[]}subscribe(a){this.A.push(a)}unsubscribe(a){a=this.A.indexOf(a);if(a===-1)return!1;this.A.splice(a,1);return!0}publish(...a){const b=[],c=this.A.slice(0);for(const d of c)b.push(d(...a));return b}};function w(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,w);else{const c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));b!==void 0&&(this.cause=b)}r(w,Error);w.prototype.name="CustomError";var ta;const ua=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(let c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},va=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){const c=a.length,d=typeof a==="string"?a.split(""):a;for(let e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)};
function wa(a){const b=a.length;if(b>0){const c=Array(b);for(let d=0;d<b;d++)c[d]=a[d];return c}return[]};var za=function(a){a:{var b=["window","location","href"];for(var c=n,d=0;d<b.length;d++)if(c=c[b[d]],c==null){b=null;break a}b=c}c=b;a==null&&(a='Unknown Error of type "null/undefined"');if(typeof a==="string")return{message:a,name:"Unknown error",lineNumber:"Not available",fileName:c,stack:"Not available"};let e,f;b=!1;try{e=a.lineNumber||a.line||"Not available"}catch(g){e="Not available",b=!0}try{f=a.fileName||a.filename||a.sourceURL||n.$googDebugFname||c}catch(g){f="Not available",b=!0}c=xa(a);
return!b&&a.lineNumber&&a.fileName&&a.stack&&a.message&&a.name?{message:a.message,name:a.name,lineNumber:a.lineNumber,fileName:a.fileName,stack:c}:(b=a.message,b==null&&(b=a.constructor&&a.constructor instanceof Function?'Unknown Error of type "'+(a.constructor.name?a.constructor.name:ya(a.constructor))+'"':"Unknown Error of unknown type",typeof a.toString==="function"&&Object.prototype.toString!==a.toString&&(b+=": "+a.toString())),{message:b,name:a.name||"UnknownError",lineNumber:e,fileName:f,stack:c||
"Not available"})},xa=function(a,b){b||(b={});b[Aa(a)]=!0;let c=a.stack||"";var d=a.cause;d&&!b[Aa(d)]&&(c+="\nCaused by: ",d.stack&&d.stack.indexOf(d.toString())==0||(c+=typeof d==="string"?d:d.message+"\n"),c+=xa(d,b));a=a.errors;if(Array.isArray(a)){d=1;let e;for(e=0;e<a.length&&!(d>4);e++)b[Aa(a[e])]||(c+="\nInner error "+d++ +": ",a[e].stack&&a[e].stack.indexOf(a[e].toString())==0||(c+=typeof a[e]==="string"?a[e]:a[e].message+"\n"),c+=xa(a[e],b));e<a.length&&(c+="\n... "+(a.length-e)+" more inner errors")}return c},
Aa=function(a){let b="";typeof a.toString==="function"&&(b=""+a);return b+a.stack},Ba=function(a){var b=Error();if(Error.captureStackTrace)Error.captureStackTrace(b,a||Ba),b=String(b.stack);else{try{throw b;}catch(c){b=c}b=(b=b.stack)?String(b):null}b||(b=Ca(a||arguments.callee.caller,[]));return b},Ca=function(a,b){const c=[];if(ua(b,a)>=0)c.push("[...circular reference...]");else if(a&&b.length<50){c.push(ya(a)+"(");const e=a.arguments;for(let f=0;e&&f<e.length;f++){f>0&&c.push(", ");var d=void 0;
d=e[f];switch(typeof d){case "object":d=d?"object":"null";break;case "string":break;case "number":d=String(d);break;case "boolean":d=d?"true":"false";break;case "function":d=(d=ya(d))?d:"[fn]";break;default:d=typeof d}d.length>40&&(d=d.slice(0,40)+"...");c.push(d)}b.push(a);c.push(")\n");try{c.push(Ca(a.caller,b))}catch(f){c.push("[exception trying to get caller]\n")}}else a?c.push("[...long stack...]"):c.push("[end]");return c.join("")},ya=function(a){if(x[a])return x[a];a=String(a);if(!x[a]){const b=
/function\s+([^\(]+)/m.exec(a);x[a]=b?b[1]:"[Anonymous]"}return x[a]},x={};function y(){this.pa=Date.now()}var Da=null;y.prototype.set=function(a){this.pa=a};y.prototype.reset=function(){this.set(Date.now())};y.prototype.get=function(){return this.pa};var z=class{constructor(a,b){this.name=a;this.value=b}toString(){return this.name}},A=new z("OFF",Infinity),Ea=new z("SHOUT",1200),Fa=new z("SEVERE",1E3),Ga=new z("WARNING",900),Ha=new z("INFO",800),Ia=new z("CONFIG",700),B=[A,Ea,Fa,Ga,Ha,Ia,new z("FINE",500),new z("FINER",400),new z("FINEST",300),new z("ALL",0)],C=null,Ja=class{constructor(){this.N=0;this.clear()}clear(){this.ea=Array(this.N);this.ga=-1;this.ia=!1}},Ka,La=class{constructor(a,b,c,d,e){this.I=void 0;this.reset(a||A,b,c,d,e)}reset(a,
b,c,d){this.ua=d||Date.now();this.Z=a;this.Ca=b;this.ja=c;this.I=void 0}getMessage(){return this.Ca}},Ma=function(a){return a.level?a.level:a.parent?Ma(a.parent):A},Na=class{constructor(a,b=null){this.level=null;this.A=[];this.parent=b||null;this.children=[];this.Ba={getName:()=>a}}publish(a){let b=this;for(;b;)b.A.forEach(c=>{c(a)}),b=b.parent}},D=function(a,b){var c=a.entries[b];if(c)return c;c=b.lastIndexOf(".");c=b.slice(0,Math.max(c,0));c=D(a,c);const d=new Na(b,c);a.entries[b]=d;c.children.push(d);
return d},Oa=class{constructor(){this.entries={};const a=new Na("");a.level=Ia;this.entries[""]=a}},Pa,E=function(){Pa||(Pa=new Oa);return Pa},Qa=function(a,b,c){var d;if(d=a)if(d=a&&b){d=b.value;var e=a?Ma(D(E(),a.getName())):A;d=d>=e.value}if(d){b=b||A;d=D(E(),a.getName());typeof c==="function"&&(c=c());Ka||(Ka=new Ja);e=Ka;a=a.getName();if(e.N>0){var f=(e.ga+1)%e.N;e.ga=f;e.ia?(e=e.ea[f],e.reset(b,c,a),a=e):(e.ia=f==e.N-1,a=e.ea[f]=new La(b,c,a))}else a=new La(b,c,a);a.I=void 0;d.publish(a)}},
Sa=function(a){var b=Ra;b&&Qa(b,Ha,a)};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
function F(a){return a.toString().indexOf("`")===-1}F(a=>a``)||F(a=>a`\0`)||F(a=>a`\n`)||F(a=>a`\u0000`);var Ta=globalThis.trustedTypes;let Ua=Ta,Va;function Wa(){let a=null;if(!Ua)return a;try{const b=c=>c;a=Ua.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(b){}return a};var G=class{constructor(a){this.la=a}toString(){return this.la+""}};function Xa(a){var b;Va===void 0&&(Va=Wa());a=(b=Va)?b.createHTML(a):a;return new G(a)}var Ya=new G(Ta?Ta.emptyHTML:"");function H(a){if(a instanceof G)return a.la;throw Error("");};var Za=class{constructor(a){this.ma=a}toString(){return this.ma}};function $a(a){return new Za(a[0])};var I=class{constructor(a){this.na=a}toString(){return this.na}},ab=new I("about:invalid#zClosurez");class bb{constructor(a){this.isValid=a}}function J(a){return new bb(b=>b.substr(0,a.length+1).toLowerCase()===a+":")}const cb=[J("data"),J("http"),J("https"),J("mailto"),J("ftp"),new bb(a=>/^[^:]*([/?#]|$)/.test(a))];function db(a,b=cb){if(a instanceof I)return a;for(let c=0;c<b.length;++c){const d=b[c];if(d instanceof bb&&d.isValid(a))return new I(a)}}var eb=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;function K(a,b){if(a instanceof G)return a;a=String(a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;");if(b==null?0:b.F)a=a.replace(/(^|[\r\n\t ]) /g,"$1&#160;");if(b==null?0:b.C)a=a.replace(/(\r\n|\n|\r)/g,"<br>");if(b==null?0:b.Ia)a=a.replace(/(\t+)/g,'<span style="white-space:pre">$1</span>');return Xa(a)}function fb(a){return L(a)}function L(a){const b=K("");return Xa(a.map(c=>H(K(c))).join(H(b).toString()))}
const gb=/^[a-z][a-z\d-]*$/i,hb="APPLET BASE EMBED IFRAME LINK MATH META OBJECT SCRIPT STYLE SVG TEMPLATE".split(" ");var ib="AREA BR COL COMMAND HR IMG INPUT KEYGEN PARAM SOURCE TRACK WBR".split(" ");const jb=["action","formaction","href"];function kb(a){if(!gb.test(a))throw Error("");if(hb.indexOf(a.toUpperCase())!==-1)throw Error("");}
function M(a,b,c){kb(a);let d=`<${a}`;b&&(d+=lb(b));Array.isArray(c)||(c=c===void 0?[]:[c]);ib.indexOf(a.toUpperCase())!==-1?d+=">":(b=fb(c.map(e=>e instanceof G?e:K(String(e)))),d+=">"+b.toString()+"</"+a+">");return Xa(d)}
function lb(a){var b="";const c=Object.keys(a);for(let f=0;f<c.length;f++){var d=c[f],e=a[d];if(!gb.test(d))throw Error("");if(e!==void 0&&e!==null){if(/^on./i.test(d))throw Error("");jb.indexOf(d.toLowerCase())!==-1&&(e instanceof I?e=e.toString():(e=String(e),e=eb.test(e)?e:void 0,e=e||"about:invalid#zClosurez"));d=`${d}="${K(String(e))}"`;b+=" "+d}}return b};"ARTICLE SECTION NAV ASIDE H1 H2 H3 H4 H5 H6 HEADER FOOTER ADDRESS P HR PRE BLOCKQUOTE OL UL LH LI DL DT DD FIGURE FIGCAPTION MAIN DIV EM STRONG SMALL S CITE Q DFN ABBR RUBY RB RT RTC RP DATA TIME CODE VAR SAMP KBD SUB SUP I B U MARK BDI BDO SPAN BR WBR NOBR INS DEL PICTURE PARAM TRACK MAP TABLE CAPTION COLGROUP COL TBODY THEAD TFOOT TR TD TH SELECT DATALIST OPTGROUP OPTION OUTPUT PROGRESS METER FIELDSET LEGEND DETAILS SUMMARY MENU DIALOG SLOT CANVAS FONT CENTER ACRONYM BASEFONT BIG DIR HGROUP STRIKE TT".split(" ").concat(["BUTTON",
"INPUT"]);var N=function(a){this.ka=a||"";Da||(Da=new y);this.sa=Da};l=N.prototype;l.da=!0;l.S=!0;l.ba=!0;l.ra=!0;l.aa=!1;l.ca=!1;
var mb=function(a){a=new Date(a.ua);return O(a.getFullYear()-2E3)+O(a.getMonth()+1)+O(a.getDate())+" "+O(a.getHours())+":"+O(a.getMinutes())+":"+O(a.getSeconds())+"."+O(Math.floor(a.getMilliseconds()/10))},O=function(a){return a<10?"0"+a:String(a)},nb=function(a,b){a=(a.ua-b)/1E3;b=a.toFixed(3);let c=0;if(a<1)c=2;else for(;a<100;)c++,a*=10;for(;c-- >0;)b=" "+b;return b},P=function(a){N.call(this,a)};r(P,N);P.prototype.aa=!0;P.prototype.ha=function(a){return a?this.X(a).toString():""};
P.prototype.X=function(a){if(!a)return Ya;switch(a.Z.value){case Ea.value:var b="dbg-sh";break;case Fa.value:b="dbg-sev";break;case Ga.value:b="dbg-w";break;case Ha.value:b="dbg-i";break;default:b="dbg-f"}var c=[];c.push(this.ka," ");this.S&&c.push("[",mb(a),"] ");this.ba&&c.push("[",nb(a,this.sa.get()),"s] ");this.ra&&c.push("[",a.ja,"] ");this.ca&&c.push("[",a.Z.name,"] ");c=K(c.join(""),{C:!0,F:!0});var d=Ya;if(this.aa&&a.I){d=M("br");try{const v=za(a.I);var e=v.fileName;e==null&&(e="");if(/^https?:\/\//i.test(e)){var f=
db(e,cb)||ab;if(f instanceof I)var g=f.na;else throw Error("");var h=new I("view-source:"+g)}else h=db("sanitizedviewsrc",cb)||ab;var k=fb([K("Message: "+v.message+"\nUrl: ",{C:!0,F:!0}),M("a",{href:h,target:"_new"},v.fileName),K("\nLine: "+v.lineNumber+"\n\nBrowser stack:\n"+v.stack+"-> [end]\n\nJS stack traversal:\n"+Ba(void 0)+"-> ",{C:!0,F:!0})])}catch(v){k=K("Exception trying to expose exception! You win, we lose. "+v,{C:!0,F:!0})}d=L([d,k])}a=K(a.getMessage(),{C:!0,F:!0});b=M("span",{"class":b},
L([a,d]));return this.da?fb([c,b,M("br")]):L([c,b])};var Q=function(a){N.call(this,a)};r(Q,N);Q.prototype.ha=function(a){const b=[];b.push(this.ka," ");this.S&&b.push("[",mb(a),"] ");this.ba&&b.push("[",nb(a,this.sa.get()),"s] ");this.ra&&b.push("[",a.ja,"] ");this.ca&&b.push("[",a.Z.name,"] ");b.push(a.getMessage());this.aa&&(a=a.I,a!==void 0&&b.push("\n",a instanceof Error?a.message:String(a)));this.da&&b.push("\n");return b.join("")};Q.prototype.X=function(a){return K(Q.prototype.ha(a),{C:!0,F:!0})};function ob(a=new Q){a.S=!0;a.ba=!1;a.ca=!0}function pb(a){a:{var b=a.l;if(!C){C={};for(let c=0,d;d=B[c];c++)C[d.value]=d,C[d.name]=d}if(b in C)b=C[b];else{for(let c=0;c<B.length;++c){let d=B[c];if(d.value<=b){b=d;break a}}b=null}}return new La(b,a.m,a.n,a.t,a.s)}D(E(),"");var qb=new z("TRACE",100);B.push(new z("DEBUG",600));B.push(qb);function rb(a,b,...c){return m(function*(){const d=new qa,e={magic:91556947316803,host:a!==null&&typeof a==="number"?"*":a,method:b,args:c},f=g=>{const h=chrome.runtime.lastError;h?d.reject(new pa(1,ka,`Operation '${String(b)}' failed. ${h.message||"Undefined error."}`)):g.error!==void 0?d.reject(sb(g.error)):d.resolve(g.result)};a!==null&&typeof a==="number"?chrome.tabs.sendMessage(a,e,f):chrome.runtime.sendMessage(e,f);return d.promise}())}
function sb(a){switch(a.type){case 0:return a.object;case 1:return Error(a.message);case 2:return new pa(a.code,oa(a.category),a.message);case 3:return new ra(a.errors.map(sb),a.message)}};var tb=function(a){for(const [c,d]of a.oa){const e=c;var b=d;if(t.every(f=>e.has(f)))return b}b={};for(const c of t)Object.defineProperty(b,c,{value:(...d)=>a.invoke(c,...d),writable:!1});a.oa.set(new Set(t),b);return b},ub=function(a){let b=a.events.get("log:record");if(!b){const c=chrome.runtime.connect({name:"log:record"}),d=new sa;b={port:c,source:d,Da:[]};c.onMessage.addListener(e=>{e=Array.isArray(e)?e:[e];const f=b.Da.shift();f?f.resolve(e.length>1?e:e[0]):d.publish(...e)});a.events.set("log:record",
b)}return b},vb=class{constructor(){this.host="*";this.events=new Map;this.oa=new Map}invoke(a,...b){const c=this;return m(function*(){return rb(c.host,a,...b)}())}};function wb(a,b){for(const c in a)b.call(void 0,a[c],c,a)};function xb(a=document){let b;const c=(b=a.querySelector)==null?void 0:b.call(a,"style[nonce]");return c==null?"":c.nonce||c.getAttribute("nonce")||""};function yb(a){if(/^(script|style)$/i.test(a.tagName))throw Error("");};function R(){var a=n.navigator;return a&&(a=a.userAgent)?a:""}var S;const zb=n.navigator;S=zb?zb.userAgentData||null:null;function T(a){return R().indexOf(a)!=-1};function U(){return!!S&&!!S.platform}function Ab(){return T("iPhone")&&!T("iPod")&&!T("iPad")};S&&S.brands.length>0||T("Opera");S&&S.brands.length>0||T("Trident")||T("MSIE");T("Edge");!T("Gecko")||R().toLowerCase().indexOf("webkit")!=-1&&!T("Edge")||T("Trident")||T("MSIE")||T("Edge");R().toLowerCase().indexOf("webkit")!=-1&&!T("Edge")&&T("Mobile");U()||T("Macintosh");U()||T("Windows");(U()?S.platform==="Linux":T("Linux"))||U()||T("CrOS");U()||T("Android");Ab();T("iPad");T("iPod");Ab()||T("iPad")||T("iPod");R().toLowerCase().indexOf("kaios");var Cb=function(a,b){wb(b,function(c,d){d=="style"?a.style.cssText=c:d=="class"?a.className=c:d=="for"?a.htmlFor=c:Bb.hasOwnProperty(d)?a.setAttribute(Bb[d],c):d.lastIndexOf("aria-",0)==0||d.lastIndexOf("data-",0)==0?a.setAttribute(d,c):a[d]=c})},Bb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},Db=function(a,
b,c,d){function e(f){f&&b.appendChild(typeof f==="string"?a.createTextNode(f):f)}for(let f=d;f<c.length;f++){const g=c[f];if(!ea(g)||p(g)&&g.nodeType>0)e(g);else{a:{if(g&&typeof g.length=="number"){if(p(g)){d=typeof g.item=="function"||typeof g.item=="string";break a}if(typeof g==="function"){d=typeof g.item=="function";break a}}d=!1}va(d?wa(g):g,e)}}},Eb=function(a,b){b=String(b);a.contentType==="application/xhtml+xml"&&(b=b.toLowerCase());return a.createElement(b)},Fb=function(a){return a.nodeType==
9?a:a.ownerDocument||a.document},V=function(a){this.H=a||n.document||document};V.prototype.getElementsByTagName=function(a,b){return(b||this.H).getElementsByTagName(String(a))};var Gb=function(a,b){a=a.H;return(b=b&&b!="*"?String(b).toUpperCase():"")?a.querySelectorAll(b+""):a.getElementsByTagName("*")};l=V.prototype;l.setProperties=Cb;
l.fa=function(a,b,c){var d=this.H,e=arguments;const f=e[1],g=Eb(d,String(e[0]));f&&(typeof f==="string"?g.className=f:Array.isArray(f)?g.className=f.join(" "):Cb(g,f));e.length>2&&Db(d,g,e,2);return g};l.createElement=function(a){return Eb(this.H,a)};l.createTextNode=function(a){return this.H.createTextNode(String(a))};l.appendChild=function(a,b){a.appendChild(b)};l.append=function(a,b){Db(Fb(a),a,arguments,1)};l.canHaveChildren=function(a){if(a.nodeType!=1)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
l.removeNode=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};l.getChildren=function(a){return a.children!=void 0?a.children:Array.prototype.filter.call(a.childNodes,function(b){return b.nodeType==1})};l.isElement=function(a){return p(a)&&a.nodeType==1};
l.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function Hb(a){q(this.U,this);this.Y=new P;this.Y.S=!1;this.g=a;this.ya=this.g.ownerDocument||this.g.document;this.xa=new V(this.ya);var b=$a`
      .dbg-sev{color:#F00}
      .dbg-w{color:#C40}
      .dbg-sh{font-weight:bold;color:#000}
      .dbg-i{color:#444}
      .dbg-f{color:#999}
      .dbg-ev{color:#0A0}
      .dbg-m{color:#990}
      .logmsg{border-bottom:1px solid #CCC;padding:2px}
      .logsep{background-color: #8C8;}
      .logdiv{border:1px solid #CCC;background-color:#FCFCFC;font:medium monospace}`;a=(a=this.g)?new V(Fb(a)):ta||(ta=new V);let c=Gb(a,"HEAD")[0];if(!c){var d=Gb(a,"BODY")[0];c=a.fa("HEAD");d.parentNode.insertBefore(c,d)}d=a.fa("STYLE");var e=xb(document);e&&d.setAttribute("nonce",e);if(b instanceof Za)b=b.ma;else throw Error("");if(n.trustedTypes)if("textContent"in d)d.textContent=b;else if(d.nodeType==3)d.data=String(b);else if(d.firstChild&&d.firstChild.nodeType==3){for(;d.lastChild!=d.firstChild;)d.removeChild(d.lastChild);
d.firstChild.data=String(b)}else{for(;e=d.firstChild;)d.removeChild(e);d.appendChild(Fb(d).createTextNode(String(b)))}else d.innerHTML=b;a.appendChild(c,d);this.g.className+=" logdiv"}Hb.prototype.U=function(a){if(a){var b=this.g.scrollHeight-this.g.scrollTop-this.g.clientHeight<=100,c=this.xa.createElement("DIV");c.className="logmsg";a=this.Y.X(a);c.nodeType===1&&yb(c);c.innerHTML=H(a);this.g.appendChild(c);b&&(this.g.scrollTop=this.g.scrollHeight)}};
Hb.prototype.clear=function(){if(this.g){var a=this.g;a.nodeType===1&&yb(a);a.innerHTML=H(Ya)}};var Jb=class{constructor(){var a=Ib;this.va=a;this.background=tb(a)}initialize(){const a=this;return m(function*(){const b=document.querySelector("#log-buffer"),c=new Hb(b);ob(c.Y);ub(a.va).source.subscribe(e=>{const f=b.scrollTop===b.scrollHeight;c.U(pb(e));f&&(b.scrollTop=b.scrollHeight)});var d=yield a.background.getLogBuffer();for(const e of d)c.U(pb(e));if(d=document.querySelector("#clear-log"))d.onclick=()=>{c.clear()};d=document.querySelectorAll("[data-i18n]");for(const e of d)d=e.getAttribute("data-i18n"),
e.textContent=chrome.i18n.getMessage(d)||"PLACEHOLDER"}())}};var W=typeof AsyncContext!=="undefined"&&typeof AsyncContext.Snapshot==="function"?a=>a&&AsyncContext.Snapshot.wrap(a):a=>a;class Kb{constructor(a,b){this.Aa=100;this.wa=a;this.Ea=b;this.R=0;this.P=null}get(){let a;this.R>0?(this.R--,a=this.P,this.P=a.next,a.next=null):a=this.wa();return a}put(a){this.Ea(a);this.R<this.Aa&&(this.R++,a.next=this.P,this.P=a)}};function Lb(a){n.setTimeout(()=>{throw a;},0)};class Mb{constructor(){this.T=this.G=null}add(a,b){const c=Nb.get();c.set(a,b);this.T?this.T.next=c:this.G=c;this.T=c}remove(){let a=null;this.G&&(a=this.G,this.G=this.G.next,this.G||(this.T=null),a.next=null);return a}}var Nb=new Kb(()=>new Ob,a=>a.reset());class Ob{constructor(){this.next=this.scope=this.fn=null}set(a,b){this.fn=a;this.scope=b;this.next=null}reset(){this.next=this.scope=this.fn=null}};let Pb,Qb=!1,Rb=new Mb,Tb=(a,b)=>{Pb||Sb();Qb||(Pb(),Qb=!0);Rb.add(a,b)},Sb=()=>{const a=Promise.resolve(void 0);Pb=()=>{a.then(Ub)}};function Ub(){let a;for(;a=Rb.remove();){try{a.fn.call(a.scope)}catch(b){Lb(b)}Nb.put(a)}Qb=!1};var Vb=function(){};var Y=function(a){this.i=0;this.qa=void 0;this.v=this.j=this.u=null;this.O=this.V=!1;if(a!=Vb)try{const b=this;a.call(void 0,function(c){X(b,2,c)},function(c){X(b,3,c)})}catch(b){X(this,3,b)}},Wb=function(){this.next=this.context=this.B=this.J=this.o=null;this.K=!1};Wb.prototype.reset=function(){this.context=this.B=this.J=this.o=null;this.K=!1};var Xb=new Kb(function(){return new Wb},function(a){a.reset()}),Yb=function(a,b,c){const d=Xb.get();d.J=a;d.B=b;d.context=c;return d};
Y.prototype.then=function(a,b,c){return Zb(this,W(typeof a==="function"?a:null),W(typeof b==="function"?b:null),c)};Y.prototype.$goog_Thenable=!0;var ac=function(a,b,c,d){$b(a,Yb(b||Vb,c||null,d))};Y.prototype.finally=function(a){a=W(a);return new Y((b,c)=>{ac(this,d=>{a();b(d)},d=>{a();c(d)})})};Y.prototype.ta=function(a,b){return Zb(this,null,W(a),b)};Y.prototype.catch=Y.prototype.ta;Y.prototype.cancel=function(a){if(this.i==0){const b=new Z(a);Tb(function(){bc(this,b)},this)}};
var bc=function(a,b){if(a.i==0)if(a.u){var c=a.u;if(c.j){var d=0,e=null,f=null;for(let g=c.j;g&&(g.K||(d++,g.o==a&&(e=g),!(e&&d>1)));g=g.next)e||(f=g);e&&(c.i==0&&d==1?bc(c,b):(f?(d=f,d.next==c.v&&(c.v=d),d.next=d.next.next):cc(c),dc(c,e,3,b)))}a.u=null}else X(a,3,b)},$b=function(a,b){a.j||a.i!=2&&a.i!=3||ec(a);a.v?a.v.next=b:a.j=b;a.v=b},Zb=function(a,b,c,d){const e=Yb(null,null,null);e.o=new Y(function(f,g){e.J=b?function(h){try{const k=b.call(d,h);f(k)}catch(k){g(k)}}:f;e.B=c?function(h){try{const k=
c.call(d,h);k===void 0&&h instanceof Z?g(h):f(k)}catch(k){g(k)}}:g});e.o.u=a;$b(a,e);return e.o};Y.prototype.Fa=function(a){this.i=0;X(this,2,a)};Y.prototype.Ga=function(a){this.i=0;X(this,3,a)};
var X=function(a,b,c){if(a.i==0){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.i=1;a:{var d=c,e=a.Fa,f=a.Ga;if(d instanceof Y){ac(d,e,f,a);var g=!0}else{if(d)try{var h=!!d.$goog_Thenable}catch(k){h=!1}else h=!1;if(h)d.then(e,f,a),g=!0;else{if(p(d))try{const k=d.then;if(typeof k==="function"){fc(d,k,e,f,a);g=!0;break a}}catch(k){f.call(a,k);g=!0;break a}g=!1}}}g||(a.qa=c,a.i=b,a.u=null,ec(a),b!=3||c instanceof Z||hc(a,c))}},fc=function(a,b,c,d,e){let f=!1;const g=function(k){f||
(f=!0,c.call(e,k))},h=function(k){f||(f=!0,d.call(e,k))};try{b.call(a,g,h)}catch(k){h(k)}},ec=function(a){a.V||(a.V=!0,Tb(a.za,a))},cc=function(a){let b=null;a.j&&(b=a.j,a.j=b.next,b.next=null);a.j||(a.v=null);return b};Y.prototype.za=function(){let a;for(;a=cc(this);)dc(this,a,this.i,this.qa);this.V=!1};
var dc=function(a,b,c,d){if(c==3&&b.B&&!b.K)for(;a&&a.O;a=a.u)a.O=!1;if(b.o)b.o.u=null,ic(b,c,d);else try{b.K?b.J.call(b.context):ic(b,c,d)}catch(e){jc.call(null,e)}Xb.put(b)},ic=function(a,b,c){b==2?a.J.call(a.context,c):a.B&&a.B.call(a.context,c)},hc=function(a,b){a.O=!0;Tb(function(){a.O&&jc.call(null,b)})},jc=Lb,Z=function(a){w.call(this,a)};r(Z,w);Z.prototype.name="cancel";var kc=function(a,b){if(typeof a!=="function")if(a&&typeof a.handleEvent=="function")a=q(a.handleEvent,a);else throw Error("Invalid listener argument");return Number(b)>2147483647?-1:n.setTimeout(a,b||0)},lc=function(a){let b=null;return(new Y(function(c,d){b=kc(function(){c(void 0)},a);b==-1&&d(Error("Failed to schedule timer."))})).ta(function(c){n.clearTimeout(b);throw c;})};const Ib=new vb,mc=tb(Ib),Ra=D(E(),"Log Script").Ba;function nc(){m(function*(){Sa("Initializing...");for(let b=1;b<=10;++b)try{yield mc.hello();break}catch(c){const d=c;if(b>=10){var a=Ra;a&&Qa(a,Fa,`Failed to communicate with background page after ${b} attempts. ${d.message}`);throw d;}yield lc(100+(15<<b))}yield(new Jb).initialize();Sa("Done.")}())}document.addEventListener("DOMContentLoaded",()=>{Sa("Handling DOMContentLoaded...");nc()});
